CREATE TABLE user (id INTEGER AUTO_INCREMENT NOT NULL, created_at DATETIME, email VARCHAR(255), name VARCHAR(255), password VARCHAR(255), username VARCHAR(255), role_id INTEGER, PRIMARY KEY (id))
CREATE TABLE roles (id INTEGER AUTO_INCREMENT NOT NULL, roleName VARCHAR(255), PRIMARY KEY (id))
CREATE TABLE products (product_id INTEGER AUTO_INCREMENT NOT NULL, code VARCHAR(255), created_at DATETIME, name VARCHAR(255), updated_at DATETIME, category_id INTEGER, PRIMARY KEY (product_id))
CREATE TABLE categories (category_id INTEGER AUTO_INCREMENT NOT NULL, created_at DATETIME, name VARCHAR(255), updated_at DATETIME, PRIMARY KEY (category_id))
CREATE TABLE sales_master (entity_id INTEGER AUTO_INCREMENT NOT NULL, base_amount DECIMAL(38), base_discount DECIMAL(38), base_tax_amount DECIMAL(38), base_total DECIMAL(38), sales_date DATETIME, user_id VARCHAR(255), PRIMARY KEY (entity_id))
CREATE TABLE vendors (vendor_id INTEGER AUTO_INCREMENT NOT NULL, address_1 VARCHAR(255), address_2 VARCHAR(255), created_at DATETIME, email VARCHAR(255), name VARCHAR(255), open_balance DECIMAL(38), phone VARCHAR(255), updated_at DATETIME, PRIMARY KEY (vendor_id))
CREATE TABLE sales_items (item_id INTEGER AUTO_INCREMENT NOT NULL, base_amount DECIMAL(38), base_discount DECIMAL(38), base_tax_amount DECIMAL(38), created_at DATETIME, qty INTEGER, product_id INTEGER, sales_id INTEGER, PRIMARY KEY (item_id))
CREATE TABLE warehouse (qty INTEGER, product_id INTEGER NOT NULL, batch_id VARCHAR(255) NOT NULL, PRIMARY KEY (product_id, batch_id))
CREATE TABLE order_master (entity_id INTEGER AUTO_INCREMENT NOT NULL, ordered_date DATETIME, order_placed_by INTEGER, vendor_id INTEGER, PRIMARY KEY (entity_id))
CREATE TABLE purchased_items (item_id INTEGER AUTO_INCREMENT NOT NULL, base_amount DECIMAL(38), base_discount DECIMAL(38), base_tax_amount DECIMAL(38), batch_id VARCHAR(255), created_at DATETIME, pruchased_qty INTEGER, updated_at DATETIME, product_id INTEGER, purchase_id INTEGER, PRIMARY KEY (item_id))
CREATE TABLE purchase_master (id INTEGER AUTO_INCREMENT NOT NULL, base_discount DECIMAL(38), base_shipping_amount DECIMAL(38), base_subtotal DECIMAL(38), base_tax_amount DECIMAL(38), base_total DECIMAL(38), created_at DATETIME, purchased_date DATETIME, updated_at VARCHAR(255), order_against_id INTEGER, vendor_id INTEGER, PRIMARY KEY (id))
CREATE TABLE store_stocks (qty INTEGER, product_id INTEGER NOT NULL, batch_id VARCHAR(255) NOT NULL, PRIMARY KEY (product_id, batch_id))
CREATE TABLE order_items (item_id INTEGER AUTO_INCREMENT NOT NULL, qty INTEGER, weight INTEGER, weight_in VARCHAR(255), order_id INTEGER, product_id INTEGER, PRIMARY KEY (item_id))
ALTER TABLE user ADD CONSTRAINT FK_user_role_id FOREIGN KEY (role_id) REFERENCES roles (id)
ALTER TABLE products ADD CONSTRAINT FK_products_category_id FOREIGN KEY (category_id) REFERENCES categories (category_id)
ALTER TABLE sales_items ADD CONSTRAINT FK_sales_items_sales_id FOREIGN KEY (sales_id) REFERENCES sales_master (entity_id)
ALTER TABLE sales_items ADD CONSTRAINT FK_sales_items_product_id FOREIGN KEY (product_id) REFERENCES products (product_id)
ALTER TABLE warehouse ADD CONSTRAINT FK_warehouse_product_id FOREIGN KEY (product_id) REFERENCES products (product_id)
ALTER TABLE order_master ADD CONSTRAINT FK_order_master_order_placed_by FOREIGN KEY (order_placed_by) REFERENCES user (id)
ALTER TABLE order_master ADD CONSTRAINT FK_order_master_vendor_id FOREIGN KEY (vendor_id) REFERENCES vendors (vendor_id)
ALTER TABLE purchased_items ADD CONSTRAINT FK_purchased_items_purchase_id FOREIGN KEY (purchase_id) REFERENCES purchase_master (id)
ALTER TABLE purchased_items ADD CONSTRAINT FK_purchased_items_product_id FOREIGN KEY (product_id) REFERENCES products (product_id)
ALTER TABLE purchase_master ADD CONSTRAINT FK_purchase_master_vendor_id FOREIGN KEY (vendor_id) REFERENCES vendors (vendor_id)
ALTER TABLE purchase_master ADD CONSTRAINT FK_purchase_master_order_against_id FOREIGN KEY (order_against_id) REFERENCES order_master (entity_id)
ALTER TABLE store_stocks ADD CONSTRAINT FK_store_stocks_product_id FOREIGN KEY (product_id) REFERENCES products (product_id)
ALTER TABLE order_items ADD CONSTRAINT FK_order_items_order_id FOREIGN KEY (order_id) REFERENCES order_master (entity_id)
ALTER TABLE order_items ADD CONSTRAINT FK_order_items_product_id FOREIGN KEY (product_id) REFERENCES products (product_id)
